-- Creating T_DOCUMENTS TABLE
CREATE TABLE T_DOCUMENTS (
    DOC_CODE INT PRIMARY KEY NOT NULL,
    DOC_FILE_PATH VARCHAR(255) NOT NULL,
    DOC_DESCRIPTION VARCHAR(255),
    DOC_CREATED_AT DATETIME,
    DOC_UPDATED_AT DATETIME,
    TDC_CODE INT NOT NULL, 
    ETU_CODE VARCHAR NOT NULL,
    CONSTRAINT FK_TDC_CODE FOREIGN KEY (TDC_CODE) REFERENCES T_TYPE_DOCUMENT(TDC_CODE),
    CONSTRAINT FK_ETU_CODE FOREIGN KEY (ETU_CODE) REFERENCES T_ETUDIANT(ETU_CODE)
);


-- creating Annee Academique table 
CREATE TABLE T_ANNEE_ACADEMIQUE (
    AAC_CODE INT PRIMARY KEY NOT NULL,
    AAC_LIB VARCHAR(255) NOT NULL,
    AAC_CREER_PAR VARCHAR(255) NOT NULL,
    AAC_MODIFIER_PAR VARCHAR(255),
    AAC_DATE_CREATION DATETIME,
    AAC_VERSION INT
);

-- creating T_FILIERE table
CREATE TABLE T_FILIERE (
    FIL_CODE INT PRIMARY KEY NOT NULL,
    FIL_LIB VARCHAR(255) NOT NULL,
    FIL_CREER_PAR VARCHAR(255) NOT NULL,
    FIL_MODIFIER_PAR VARCHAR(255),
    FIL_DATE_CREATION DATETIME,
    FIL_VERSION INT
)

-- creating T_NIVEAU table
CREATE TABLE T_NIVEAU (
    NIV_CODE INT PRIMARY KEY NOT NULL,
    NIV_LIB VARCHAR(255) NOT NULL,
    NIV_CREER_PAR VARCHAR(255) NOT NULL,
    NIVEAU_MODIFIER_PAR VARCHAR(255),
    NIVEAU_DATE_CREATION DATETIME,
    NIVEAU_VERSION INT
);