-- Creating T_DOCUMENTS TABLE
CREATE TABLE T_DOCUMENTS (
    DOC_CODE INT PRIMARY KEY NOT NULL,
    DOC_FILE_PATH VARCHAR(255) NOT NULL,
    DOC_DESCRIPTION VARCHAR(255),
    DOC_CREATED_AT DATETIME,
    DOC_UPDATED_AT DATETIME,
    TDC_CODE INT NOT NULL, 
    ETU_CODE VARCHAR NOT NULL,
    CONSTRAINT FK_TDC_CODE FOREIGN KEY (TDC_CODE) REFERENCES T_TYPE_DOCUMENT(TDC_CODE),
    CONSTRAINT FK_ETU_CODE FOREIGN KEY (ETU_CODE) REFERENCES T_ETUDIANT(ETU_CODE)
);


